# ╔══════════════════════════════════════════════════════════╗
# ║           NixOS Configuration — naranyala              ║
# ║           GNOME / Wayland / 25.05                       ║
# ╚══════════════════════════════════════════════════════════╝
#
# ── Channel setup (run once) ─────────────────────────────
#   sudo nix-channel --add https://github.com/nix-community/home-manager/archive/release-25.05.tar.gz home-manager
#   sudo nix-channel --add https://github.com/nix-community/nix-snapd/archive/main.tar.gz nix-snapd
#   sudo nix-channel --update
#
# ── Common commands ───────────────────────────────────────
#   sudo nixos-rebuild switch            # Apply config now
#   sudo nixos-rebuild switch --upgrade  # Upgrade pkgs + apply
#   sudo nixos-rebuild boot              # Apply on next boot (safe)
#   sudo nixos-rebuild switch --rollback # Undo last switch
#   sudo nixos-rebuild boot --rollback   # Rollback on next boot
#   nix-env --list-generations --profile /nix/var/nix/profiles/system
#   sudo nix-collect-garbage -d          # Delete old generations
#
# ── Troubleshooting ──────────────────────────────────────
#   journalctl -b -p err                   # Boot errors
#   systemctl --failed                     # Failed services
#   nix-store --verify --check-contents    # Corrupt store check
#   sudo nixos-option <option>             # Inspect any option
#
# ── Useful references ────────────────────────────────────
#   https://search.nixos.org/options       # Search all options
#   https://search.nixos.org/packages      # Search all packages
#   https://nixos.wiki                     # Community wiki
#   https://home-manager-options.extranix.com  # Home Manager options

{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix       # Auto-generated by nixos-generate-config
    <home-manager/nixos>               # Home Manager NixOS module
    (import <nix-snapd>).nixosModules.default  # Snap support (commented out below)
  ];

  # ═══════════════════════════════════════════════════════
  # 0. NIX SETTINGS
  #
  # Controls how the Nix package manager itself behaves:
  #   - experimental-features: unlocks the modern `nix` CLI
  #     and flake support (needed even if using channels today)
  #   - auto-optimise-store: hard-links identical files across
  #     generations, typically saving 1-3 GB on disk
  #   - gc: auto-deletes generations older than 7 days weekly
  #   - keep-derivations: keeps .drv files so rebuilds are faster
  #
  # FUTURE IMPROVEMENTS:
  #   • Migrate to flake.nix for full reproducibility
  #     (pins every input with a lock file — no channel drift)
  #   • Add `nix.settings.substituters` for binary caches
  #     (e.g. `https://nix-community.cachix.org`)
  #   • Set `nix.settings.trusted-users = [ "naranyala" ]` to
  #     avoid sudo for nix commands on single-user machines
  # ═══════════════════════════════════════════════════════
  nix = {
    settings.experimental-features = [ "nix-command" "flakes" ];
    settings.auto-optimise-store = true;
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 7d";
    };
    settings.keep-outputs = false;
    settings.keep-derivations = true;
  };

  # ═══════════════════════════════════════════════════════
  # 1. BOOT & KERNEL
  #
  # systemd-boot: fast, minimal boot loader for UEFI systems.
  #   Alternatives: grub (legacy BIOS / dual-boot), limine, rEFInd.
  # efi.canTouchEfiVariables: lets the loader write boot entries
  #   to UEFI NVRAM. Set false on VMs or broken firmware.
  #
  # FUTURE IMPROVEMENTS:
  #   • Add `boot.kernelPackages = pkgs.linuxPackages_latest;`
  #     for newer hardware support (Wi-Fi 7, newer GPUs)
  #   • Add `boot.kernelParams = [ "quiet" "splash" "mitigations=off" ];`
  #     for boot speed (mitigations=off is a security trade-off)
  #   • Enable `boot.initrd.systemd.enable = true` for faster boot
  #     with systemd in the initrd phase
  #   • Add `boot.tmp.cleanOnBoot = true` if /tmp accumulates garbage
  # ═══════════════════════════════════════════════════════
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  # NTFS partition fix — uncomment only if Windows dual-boot
  # and NTFS volumes fail to mount. ntfsfix clears the Windows
  # "dirty" flag; it does NOT repair actual filesystem corruption.
  #
  # boot.initrd.postDeviceCommands = ''
  #   ${pkgs.ntfs3g}/bin/ntfsfix /dev/sda2
  #   ${pkgs.ntfs3g}/bin/ntfsfix /dev/nvme0n1p4
  # '';
  #
  # Better approach: use the modern kernel ntfs3 driver instead:
  #   boot.extraModulePackages = [ config.boot.kernelPackages.ntfs3 ];
  #   boot.supportedFilesystems = [ "ntfs" ];

  # ═══════════════════════════════════════════════════════
  # 2. NETWORKING & FIREWALL
  #
  # NetworkManager: the standard desktop network manager.
  #   Handles Wi-Fi, Ethernet, VPN (via GNOME settings).
  #   Alternative: systemd-networkd (headless / servers).
  #
  # Firewall rules below are for:
  #   TCP 57621 — Spotify Connect device discovery
  #   UDP 5353  — mDNS/Bonjour (Spotify + local network discovery)
  #
  # FUTURE IMPROVEMENTS:
  #   • Add `networking.wireless.enable = true;` if not using NM
  #     (rarely needed on desktop; NM handles Wi-Fi better)
  #   • Add `networking.hosts` for local DNS overrides:
  #       networking.hosts = {
  #         "127.0.0.1" = [ "dev.local" "api.local" ];
  #       };
  #   • Add `services.openssh.enable = true;` for remote access
  #   • Add `services.tailscale.enable = true;` for zero-config VPN
  #     to access this machine from anywhere
  # ═══════════════════════════════════════════════════════
  networking.hostName = "nixos";
  networking.networkmanager.enable = true;

  networking.firewall = {
    allowedTCPPorts = [ 57621 ];   # Spotify Connect discovery
    allowedUDPPorts = [ 5353 ];    # mDNS / Bonjour
    # allowedTCPPortRanges = [ 8000 8010 ];  # open a range (dev servers)
  };

  # Snap support — uncomment only if you actually use snap packages.
  # Most snap packages have Nix equivalents. Adds a persistent daemon.
  # On NixOS, prefer: nix packages > flatpak > snap (in that order).
  # services.snap.enable = true;

  # ═══════════════════════════════════════════════════════
  # 3. LOCALE & TIME
  #
  # timeZone: affects how timestamps are displayed.
  # defaultLocale: the system language for apps and terminals.
  #
  # FUTURE IMPROVEMENTS:
  #   • Add `i18n.supportedLocales` to generate only needed locales
  #     (speeds up nixos-rebuild):
  #       i18n.supportedLocales = [
  #         "en_US.UTF-8/UTF-8"
  #         "id_ID.UTF-8/UTF-8"   # Indonesian
  #       ];
  #   • Add `console = { font = "Lat2-Terminus16"; keyMap = "us"; };`
  #     for TTY (Ctrl+Alt+F3) font and keyboard layout
  # ═══════════════════════════════════════════════════════
  time.timeZone = "Asia/Jakarta";
  i18n.defaultLocale = "en_US.UTF-8";

  # ═══════════════════════════════════════════════════════
  # 4. DISPLAY SERVER — GNOME / Wayland
  #
  # GDM + Wayland: modern display manager with Wayland by default.
  # GNOME is the full desktop environment. Wayland is the display
  # protocol (more secure than X11, no screen tearing).
  #
  # xkb: keyboard layout. "us" = US QWERTY.
  #   Common alternatives: "us" variant "intl" for dead keys,
  #   "id" for Indonesian layout, "de" for German.
  #
  # xdg.portal: allows sandboxed apps (Flatpak, Firefox snap) to
  #   access host resources like file dialogs, screen sharing.
  #   xdg-desktop-portal-gtk: GTK file picker dialog.
  #
  # GNOME debloating: removes ~2 GB of default GNOME apps.
  #   These are still available via `nix-env -iA` if needed later.
  #
  # dconf: GNOME's configuration database (like Windows Registry
  #   for GNOME). Used here for dark theme and cursor locate.
  #
  # gnome-keyring: stores passwords, SSH keys, and secrets.
  #   Needed by Chrome/Chromium, VS Code, and many apps.
  #
  # FUTURE IMPROVEMENTS:
  #   • Add more dconf settings:
  #       "org/gnome/shell/extensions/dash-to-panel" = {
  #         dock-position = "BOTTOM";
  #         panel-sizes = { "0" = 48; };
  #       };
  #   • Add `services.gnome.gnome-initial-setup.enable = false;`
  #     to skip the first-boot GNOME setup wizard
  #   • Add `services.libinput.enable = true;` for better touchpad
  #     gesture support (1:1 touchpad, natural scrolling)
  #   • Add `environment.gnome.excludeGSettings` to suppress
  #     specific GSettings schemas
  #   • Enable fractional scaling:
  #       services.xserver.dpi = 144;  # for 150% on HiDPI
  # ═══════════════════════════════════════════════════════

  # desktop-gnome
  # services.xserver.enable = true;
  # services.displayManager.gdm.enable = true;
  # services.desktopManager.gnome.enable = true;

  # desktop-kde-plasma
  services.desktopManager.plasma6.enable = true;
  services.displayManager.sddm.enable = true;
  services.displayManager.sddm.wayland.enable = true;

  # desktop-xfce
  # services.xserver.enable = true;
  # services.xserver.displayManager.lightdm.enable = true;
  # services.xserver.desktopManager.xfce.enable = true;

  xdg.portal = {
    enable = true;
    extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
    # wlr.enable = true;  # needed for Sway/Hyprland screen sharing
  };

  environment.gnome.excludePackages = with pkgs; [];

  programs.dconf.enable = true;
  programs.dconf.profiles.user.databases = [{
    settings = {
      "org/gnome/desktop/interface" = {
        color-scheme = "prefer-dark";
        cursor-theme = "Adwaita";
        locate-pointer = true;  # Ctrl = highlight cursor
      };
    };
  }];

  services.gnome.gnome-keyring.enable = true;

  # ═══════════════════════════════════════════════════════
  # 5. AUDIO — PipeWire (PulseAudio disabled)
  #
  # PipeWire replaces PulseAudio, JACK, and parts of ALSA.
  # It handles: desktop audio, pro audio (JACK compat),
  # Bluetooth audio, and screen sharing (via xdg-desktop-portal).
  #
  # rtkit: real-time kernel scheduling for low-latency audio.
  #
  # Low-latency config:
  #   quantum = 512  → ~10.7ms latency (good balance)
  #   min = 32       → ~0.67ms (for pro audio needs)
  #   max = 1024     → ~21.3ms (prevents crackling under load)
  #
  # Bluetooth tweaks:
  #   sbc-xq: higher-quality SBC codec
  #   mSBC: wideband speech for headsets
  #   hw-volume: let the headset control volume
  #
  # FUTURE IMPROVEMENTS:
  #   • Add EasyEffects user config in home-manager (see §15):
  #       xdg.configFile."EasyEffects/input/mic-denoise.json".source = ...
  #       xdg.configFile."EasyEffects/output/equalizer.json".source = ...
  #   • Add `services.pipewire.wireplumber.config."wireplumber/settings"`
  #     for per-device sample rate overrides
  #   • For audiophile setups: `default.clock.rate = 96000;`
  #     + matching DAC hardware
  #   • Add `services.pulseaudio.enable = false;` is already set.
  #     If a legacy app needs PulseAudio, PipeWire provides the
  #     `pipewire-pulse` compatibility layer (enabled above).
  # ═══════════════════════════════════════════════════════
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    jack.enable = true;

    extraConfig.pipewire."92-low-latency" = {
      "context.properties" = {
        "default.clock.rate" = 48000;
        "default.clock.quantum" = 512;
        "default.clock.min-quantum" = 32;
        "default.clock.max-quantum" = 1024;
      };
    };

    wireplumber.extraConfig = {
      "10-bluez" = {
        "monitor.bluez.properties" = {
          "bluez5.enable-sbc-xq" = true;
          "bluez5.enable-msbc" = true;
          "bluez5.enable-hw-volume" = true;
          "bluez5.roles" = [
            "a2dp_sink" "a2dp_source"
            "headset_head_unit" "headset_audio_gateway"
          ];
        };
      };
    };
  };
  services.pulseaudio.enable = false;

  # ═══════════════════════════════════════════════════════
  # 6. PRINTING & EXTERNAL FORMATS
  #
  # CUPS: the Common UNIX Printing System. ~150-250 MB.
  #   If you don't own a printer, comment this out.
  #   For HP printers, also add `services.printing.drivers = [ pkgs.hplip ];`
  #
  # AppImage: lets you run .AppImage files by double-clicking.
  #   binfmt = registers the AppImage format with the kernel
  #   so you can run them directly without chmod +x.
  #
  # nix-ld: allows running non-Nix binaries (AppImage internals,
  #   proprietary software, pre-built binaries from the web).
  #   It provides a /lib64/ld-linux-x86-64.so.2 shim that
  #   dynamically links to Nix store libraries.
  #   Only add custom libraries here if a specific binary fails
  #   with a clear "library not found" error.
  #
  # FUTURE IMPROVEMENTS:
  #   • Add `services.avahi.enable = true;` for network discovery
  #     (printers, scanners, Spotify Connect without open firewall)
  #     Add `services.avahi.nssmdns4 = true;` for .local resolution
  #   • Add Flatpak support as an alternative to nix-ld/AppImage:
  #       services.flatpak.enable = true;
  #   • Add `hardware.sane.enable = true;` for scanner support
  # ═══════════════════════════════════════════════════════
  services.printing.enable = true;

  programs.appimage.enable = true;
  programs.appimage.binfmt = true;

  programs.nix-ld.enable = true;
  # Only add libraries below when a specific binary fails:
  # programs.nix-ld.libraries = with pkgs; [
  #   nspr nss libdrm mesa alsa-lib atk at-spi2-atk at-spi2-core
  #   cairo cups dbus expat fontconfig freetype gdk-pixbuf glib
  #   gtk3 libGL pango pciutils udev libgbm libxkbcommon
  #   xorg.libxcb xorg.libX11 xorg.libXcomposite xorg.libXcursor
  #   xorg.libXdamage xorg.libXext xorg.libXfixes xorg.libXi
  #   xorg.libXrandr xorg.libXrender xorg.libXScrnSaver xorg.libXtst
  #   xorg.libxshmfence
  # ];

  # ═══════════════════════════════════════════════════════
  # 7. SWAY / TILING WM PACKAGES (commented out)
  #
  # Sway is a Wayland-native tiling window manager (i3 replacement).
  # You are using GNOME as your primary DE, so these packages are
  # not needed. They are kept here as reference if you ever want
  # to add a Sway session alongside GNOME.
  #
  # If switching to Sway as primary DE:
  #   1. Uncomment `programs.sway` and the sway-* packages
  #   2. Set `services.xserver.desktopManager.gnome.enable = false;`
  #   3. Uncomment the declarative configs below
  #   4. Remove GNOME extensions from desktopManager.gnome.extraPackages
  #
  # Alternative tiling WMs to consider:
  #   • Hyprland — animated, modern Wayland compositor (very popular)
  #   • River — dynamic tag-based Wayland compositor
  #   • i3 — X11 version of Sway (if you need X11 compatibility)
  # ═══════════════════════════════════════════════════════
  # programs.sway = {
  #   enable = true;
  #   wrapperFeatures.gtk = true;
  #   extraPackages = with pkgs; [ swaylock swayidle ];
  # };

  # Sway-specific packages (only when using Sway):
  # waybar fuzzel mako grim slurp foot wl-clipboard

  # environment.etc."sway/config".text = ''
  #   set $mod Mod4
  #   bindsym $mod+Return exec foot
  #   bindsym $mod+d exec fuzzel
  #   bindsym $mod+Shift+q kill
  #   bindsym $mod+Shift+c reload
  #   bindsym $mod+Shift+e exec "swaymsg exit"
  #   bar { swaybar_command waybar }
  # '';

  # environment.etc."fuzzel/fuzzel.ini".text = ''
  #   [main]
  #   font=JetBrains Mono 12
  #   terminal=foot
  #   layer=overlay
  #   prompt=Search:
  #   [colors]
  #   background=#1e1e2e
  #   text=#cdd6f4
  #   selection=#89b4fa
  # '';

  # programs.waybar.enable = true;
  # environment.etc."waybar/config".text = ''
  #   {
  #     "layer": "top",
  #     "position": "top",
  #     "modules-left": ["sway/workspaces", "sway/mode"],
  #     "modules-center": ["clock"],
  #     "modules-right": ["pulseaudio", "network", "battery", "tray"]
  #   }
  # '';
  # environment.etc."waybar/style.css".text = ''
  #   * { font-family: "JetBrains Mono", monospace; font-size: 12px; }
  #   #clock { color: #ffffff; }
  #   #battery { color: #00ff00; }
  # '';

  # ═══════════════════════════════════════════════════════
  # 8. USERS
  #
  # isNormalUser: creates a regular user (not root/system).
  # extraGroups:
  #   wheel      → allows sudo
  #   networkmanager → allows managing network connections
  #   Other common groups: docker, video, audio, plugdev, libvirtd
  #
  # FUTURE IMPROVEMENTS:
  #   • Add `users.mutableUsers = false;` to enforce that
  #     only passwords defined here exist (clears others on rebuild)
  #   • Add `users.users.naranyala.hashedPassword = "...";`
  #     for declarative password: `mkpasswd -m sha-512`
  #   • Add `users.users.naranyala.openssh.authorizedKeys.keys = [ ... ];`
  #     for SSH key authentication
  #   • Add `users.users.naranyala.packages = with pkgs; [ ... ];`
  #     as an alternative to home-manager for simple setups
  #   • Add `security.sudo.wheelNeedsPassword = false;` for
  #     passwordless sudo (like macOS default)
  # ═══════════════════════════════════════════════════════
  users.users.naranyala = {
    isNormalUser = true;
    description  = "naranyala";
    extraGroups  = [ "networkmanager" "wheel" "docker" ];
    # shell = pkgs.zsh;  # change default shell
    # openssh.authorizedKeys.keys = [
    #   "ssh-ed25519 AAAA... your-key"
    # ];
  };

  # ═══════════════════════════════════════════════════════
  # 9. SYSTEM PACKAGES
  #
  # These packages are available to ALL users on the system.
  # Only truly system-wide packages belong here (browsers,
  # creative apps, system utilities).
  #
  # Personal dev tools (compilers, languages, CLI utilities,
  # editors) should go in home-manager (§15) to:
  #   • Keep the system closure smaller and faster to build
  #   • Allow per-user package customization
  #   • Make multi-user setups cleaner
  #
  # Package search: https://search.nixos.org/packages
  #
  # Zen Browser note: fetchTarball without sha256 re-downloads
  # on every rebuild. Pin with:
  #   nix-prefetch-url --unpack https://github.com/0xc000022070/zen-browser-flake/archive/<commit>.tar.gz
  #
  # FUTURE IMPROVEMENTS:
  #   • Move dev tools to home-manager: nodejs, python, rust,
  #     zig, odin, vlang, bun, uv, typescript, gcc, clang, etc.
  #   • Add `nixpkgs.config.permittedInsecurePackages = [ ... ];`
  #     if you need insecure/old packages
  #   • Use overlays instead of direct pkgs for custom package
  #     modifications:
  #       nixpkgs.overlays = [
  #         (self: super: {
  #           firefox = super.firefox.override { ... };
  #         })
  #       ];
  #   • Add `hardware.enableAllFirmware = true;` for proprietary
  #     firmware blobs (Wi-Fi cards, GPUs)
  # ═══════════════════════════════════════════════════════
  nixpkgs.config.allowUnfree = true;

  environment.systemPackages = let
    jan-ai = pkgs.appimageTools.wrapType2 {
      pname = "jan";
      name = "jan";
      version = "0.7.9";
      src = pkgs.fetchurl {
        url = "https://github.com/janhq/jan/releases/download/v0.7.9/Jan_0.7.9_amd64.AppImage";
        sha256 = "48c7238a0e89fc70a92ed853f1d1c2eb2103eaeb87c9a4c6ff12e75089591cff";
      };
      extraPkgs = pkgs: with pkgs; [ libsecret libglvnd vulkan-loader ];
    };

    helium-browser = pkgs.appimageTools.wrapType2 {
      pname = "helium";
      name = "helium";
      version = "0.11.6.1";
      src = pkgs.fetchurl {
        url = "https://github.com/imputnet/helium-linux/releases/download/0.11.6.1/helium-0.11.6.1-x86_64.AppImage";
        sha256 = "36fb1255e2abf36304f283eea54f0eca1f486d87abc40589e6f463be3e16c8ba";
      };
      extraPkgs = pkgs: with pkgs; [
        nss nspr dbus libdrm xorg.libXdamage xorg.libX11
        alsa-lib mesa libglvnd
      ];
    };

    # lm-studio = pkgs.appimageTools.wrapType2 {
    #   pname = "lm-studio";
    #   name = "lm-studio";
    #   version = "latest";
    #   src = pkgs.fetchurl {
    #     url = "https://lmstudio.ai/download/latest/linux/x64?format=AppImage";
    #     sha256 = "53b4c990c52a98be1693bef3708376ff8205cfb6abb6f560d2c691123a06cbc2";
    #   };
    #   extraPkgs = pkgs: with pkgs; [
    #     nss nspr dbus libdrm xorg.libXdamage xorg.libX11
    #     alsa-lib mesa libglvnd vulkan-loader
    #   ];
    # };

    zen-repo = import (builtins.fetchTarball {
      url = "https://github.com/0xc000022070/zen-browser-flake/archive/main.tar.gz";
      # sha256 = "sha256-PLACEHOLDER — run: nix-prefetch-url --unpack <url>";
    }) {
      inherit pkgs;
    };
  in with pkgs; [
    glib

    # ── Browsers ────────────────────────────────────────
    zen-repo.default
    floorp
    chromium

    # ── Custom AppImage Wrappers ────────────────────────
    jan-ai
    helium-browser
    # lm-studio  # Disabled - uncomment to enable

    # ── Music / Audio ──────────────────────────────────
    spotify
    easyeffects
    lsp-plugins
    rnnoise-plugin
    pavucontrol

    # ── Office / Creative ──────────────────────────────
    onlyoffice-desktopeditors
    inkscape
    drawio
    blender
    freecad
    qgis

    docker

    # ── Additional Production Apps ──────────────────
    # Enable as needed:
    # vscode
    # postman
    # slack
    # discord
    # remmina  # RDP client for Windows servers
    # virt-manager  # VM management
    # cockpit  # Web-based server management

    # ── GNOME Extensions / Tweaks ──────────────────────
    # NOTE: These require GNOME desktop, currently using XFCE
    # gnome-tweaks
    # gnomeExtensions.dash-to-panel
    # gnomeExtensions.arc-menu
    # gnomeExtensions.appindicator
    # gnomeExtensions.blur-my-shell

    # ── System Utilities ───────────────────────────────
    pkg-config
    ntfs3g
    steam-run-free
    adwaita-icon-theme
    libglibutil
    copyDesktopItems
    wrapGAppsHook4

    # ── Cross-DE Apps (work on any desktop) ────────────
    kdePackages.kdenlive  # Best Linux video editor
    # kdePackages.dolphin  # Power file manager
    evince               # PDF viewer (universal)
    # eog               # Image viewer
  ];

  # ═══════════════════════════════════════════════════════════
  # §X. MIXED DESKTOP APPS REFERENCE (uncomment to install)
  #
  # These apps work on ANY desktop (KDE, GNOME, XFCE) - just enable what you need
  # ─────────────────────────────────────────────────────────────
  # KDE Apps (Qt-based, polished):
  #   kdePackages.kdenlive     # Video editor (best on Linux)
  #   kdePackages.dolphin      # File manager (power user)
  #   kdePackages.kate         # Text editor
  #   kdePackages.konsole      # Terminal
  #   kdePackages.spectacle   # Screenshot
  #   kdePackages.okular      # PDF viewer
  #   kdePackages.ark         # Archive manager
  #   kdePackages.gwenview    # Image viewer
  #   kdePackages.kcalc       # Calculator
  # GNOME Apps (GTK-based):
  #   gnome-tweaks            # Tweak tool
  #   nautilus              # File manager
  #   gnome-screenshot    # Screenshot
  #   evince               # PDF viewer
  #   eog                 # Image viewer
  #   gedit                # Text editor
  #   geary                # Email client
  #   totem                # Video player
  # XFCE Apps (lightweight):
  #   thunar               # File manager
  #   ristretto            # Image viewer
  #   mousepad            # Text editor

  # ═══════════════════════════════════════════════════════════
  # 10. SHELL ALIASES (system-wide)
  #
  # Available to all users and all shells (bash, zsh, fish).
  # For user-specific aliases, use home-manager (§15).
  #
  # FUTURE IMPROVEMENTS:
  #   • Add nix development aliases:
  #       nix-build-pkg = "nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'";
  #   • Add container shortcuts:
  #       dclean = "docker system prune -af && docker volume prune -f";
  #   • Add a quick nixos config test:
  #       nix-test = "sudo nixos-rebuild dry-activate";
  # ═══════════════════════════════════════════════════════
  environment.shellAliases = {
    # NixOS helpers
    nix-switch = "sudo nixos-rebuild switch";
    nix-clean  = "sudo nix-collect-garbage -d";
    nix-config = "nano /etc/nixos/configuration.nix";

    # Windows-like shortcuts
    dir      = "ls -alh";
    cls      = "clear";
    explorer = "nautilus .";

    # NixOS config editing
    edit-nixos-ssd  = "sudo nvim /etc/nixos/configuration.nix";
    edit-nixos-ext  = "sudo nvim /media/naranyala/ext_root/etc/nixos/configuration.nix";

    # Project navigation (requires external drives mounted)
    goto-project-remote    = "cd /media/naranyala/Data/projects-remote";
    goto-project-agentic   = "cd /media/naranyala/Data/projects-agentic";
    goto-project-pi        = "cd /media/naranyala/Data/projects-pi-ext";
    mergepdf-cwd           = "bun /media/naranyala/Data/diskd-scripts/javascript/merge-all-pdf-in-current-dir.js";
    goto-diskd-bin         = "cd /media/naranyala/Data/diskd-binaries";
    battery-health         = "upower -i /org/freedesktop/UPower/devices/battery_BAT0";
    show-pi                = "bat ~/.pi/agent/settings.json";
    goto-config-opencode   = "cd ~/.config/opencode";
    goto-config-pi         = "cd ~/.pi/agent";
    goto-ai-runner         = "cd /media/naranyala/Data/diskd-binaries/llm-stack";
    goto-ai-models         = "cd /home/naranyala/.lmstudio/models/lmstudio-community";

    # Development
    gitlog = "git log --oneline --graph --decorate";
  };

  # ═══════════════════════════════════════════════════════
  # 11. ENVIRONMENT VARIABLES
  #
  # Set for ALL users. For user-specific vars, use home-manager.
  #
  # NOTE: NixOS automatically handles PKG_CONFIG_PATH, CFLAGS,
  # LDFLAGS, etc. via wrapGAppsHook4 and Nix wrappers. Setting
  # them manually usually causes conflicts. Only uncomment if
  # a specific non-Nix binary requires them.
  #
  # NPM_CONFIG_PREFIX: tells npm to install global packages
  # to ~/.npm-packages instead of the Nix store (which is
  # read-only). Add $HOME/.npm-packages/bin to PATH to use them.
  #
  # FUTURE IMPROVEMENTS:
  #   • Add `XDG_CONFIG_HOME = "$HOME/.config";` for apps that
  #     don't default to the XDG standard
  #   • Add `EDITOR = "nvim";` if neovim becomes your daily driver
  #   • Add `TERMINAL = "foot";` or your preferred terminal
  #   • Add `MOZ_ENABLE_WAYLAND = "1";` for Firefox Wayland native
  #   • Add `ELECTRON_OZONE_PLATFORM_HINT = "wayland";` for
  #     Electron apps (Discord, Slack, etc.) on Wayland
  # ═══════════════════════════════════════════════════════
  environment.variables = {
    EDITOR  = "nano";
    BROWSER = "firefox";
    NPM_CONFIG_PREFIX = "$HOME/.npm-packages";

    # Uncomment only if a specific non-Nix binary needs them:
    PKG_CONFIG_PATH  = "${pkgs.glib.dev}/lib/pkgconfig:${pkgs.glib.out}/lib/pkgconfig";
    CFLAGS           = "-I${pkgs.glib.dev}/include/glib-2.0 -I${pkgs.glib.dev}/lib/glib-2.0/include";
    LDFLAGS          = "-L${pkgs.glib.out}/lib -L${pkgs.gtk3.out}/lib";
    GIO_MODULE_DIR   = "${pkgs.glib.out}/lib/gio/modules";
    GST_PLUGIN_PATH  = "${pkgs.gst_all_1.gstreamer.out}/lib/gstreamer-1.0";
    MOZ_ENABLE_WAYLAND = "1";
    ELECTRON_OZONE_PLATFORM_HINT = "wayland";

    # cause failure to compile
    # LD_LIBRARY_PATH  = "${pkgs.glib.out}/lib:${pkgs.gtk3.out}/lib";
    # XDG_DATA_DIRS    = "${pkgs.gtk3.out}/share:${pkgs.glib.out}/share";
  };

  # Session PATH additions — directories added to $PATH for all users
  environment.sessionVariables = {
    PATH = [
      "$HOME/.npm-packages/bin"
      "$HOME/.local/bin"
      "$HOME/bin"
      "$HOME/.bun/bin"
      # WARNING: These depend on external drives being mounted.
      # If the drive isn't mounted, these entries are harmless but
      # produce "directory not found" warnings in some tools.
      # Consider systemd.automount for on-demand mounting:
      #   systemd.mounts = [{
      #     what = "/dev/disk/by-uuid/XXXX";
      #     where = "/media/naranyala/Data";
      #     type = "ext4";
      #     options = "nofail,x-systemd.automount,x-systemd.idle-timeout=60";
      #   }];
      "/media/naranyala/Data/diskd-binaries"
      "/media/naranyala/Data/diskd-binaries/v_linux"
      "/media/naranyala/Data/diskd-binaries/zig-x86_64-linux-0.15.2"
      "/media/naranyala/Data/diskd-binaries/odin-linux"
      "/media/naranyala/Data/diskd-binaries/c3-linux"
    ];
  };

  # ═══════════════════════════════════════════════════════
  # 12. DATABASE — PostgreSQL
  #
  # Runs a PostgreSQL 17 server as a systemd service.
  #   ensureDatabases: creates databases on first activation
  #   ensureUsers: creates roles that can connect
  #   ensurePermissions: grants access to the database
  #
  # Data directory: /var/lib/postgresql/17
  # Backup: pg_dump mydatabase > backup.sql
  # Restore: psql mydatabase < backup.sql
  #
  # FUTURE IMPROVEMENTS:
  #   • Add `services.postgresql.enableTCPIP = true;` and
  #     `services.postgresql.authentication = "scram-sha-256";`
  #     for remote access (with firewall rules!)
  #   • Add `services.postgresql.initialScript` to run custom
  #     SQL on first boot (create schemas, extensions)
  #   • Add Redis for caching: `services.redis.enable = true;`
  #   • Add SQLite: already included as a package (serverless,
  #     no service needed)
  #   • Add MySQL/MariaDB: `services.mysql.enable = true;`
  #   • Add `services.postgresql.backup = { ... };` for
  #     automated pg_dump cron jobs
  # ═══════════════════════════════════════════════════════
  services.postgresql = {
    enable = true;
    package = pkgs.postgresql_17;
    ensureDatabases = [ "mydatabase" ];
    ensureUsers = [{
      name = "myuser";
    }];
    # ensurePermissions = {
    #   "myuser.mydatabase" = "ALL PRIVILEGES";
    # };
  };

  # ═══════════════════════════════════════════════════════
  # 13. ACTIVATION SCRIPTS
  #
  # Activation scripts run on EVERY rebuild, before the new
  # system becomes active. They must be idempotent (safe to
  # run multiple times with the same result).
  #
  # REMOVED: system.activationScripts.myScript
  #   This previously ran `curl | bash` every rebuild — a
  #   security risk (supply chain attack vector) and
  #   non-idempotent (bun install -g fails on re-run).
  #
  # To install Claude CLI and Gemini CLI:
  #   curl -fsSL https://claude.ai/install.sh | bash
  #   bun install -g @google/gemini-cli@latest
  #
  # Or better: wait for proper Nix derivations and add them
  # to environment.systemPackages or home-manager.
  #
  # FUTURE IMPROVEMENTS:
  #   • If you need a one-time setup script, use:
  #       system.activationScripts.mySetup.text = ''
  #         [ -f /path/to/marker ] || {
  #           echo "Running one-time setup..."
  #           touch /path/to/marker
  #         }
  #       '';
  #   • For file sync on rebuild, consider impermanence:
  #       https://github.com/nix-community/impermanence
  # ═══════════════════════════════════════════════════════

  # ═══════════════════════════════════════════════════════
  # 14. SYSTEM-WIDE PROGRAMS
  #
  # `programs.*` options enable features that affect all users.
  # These are higher-level than packages — they configure
  # services, shell integration, and defaults.
  #
  # Firefox: system-wide installation available via GDM login.
  # Starship: cross-shell prompt (git status, lang versions, etc.)
  #
  # FUTURE IMPROVEMENTS:
  #   • Add `programs.zsh.enable = true;` for system-wide zsh
  #     with tab completion and syntax highlighting
  #   • Add `programs.bash.enableCompletion = true;` for
  #     bash tab completion (packages + nix commands)
  #   • Add `programs.nix-ld.enable = true;` — already in §6
  #   • Add `programs.gnupg.agent.enable = true;` for GPG agent
  #     with SSH support (replaces ssh-agent)
  #   • Add `services.devmon.enable = true;` for auto-mounting
  #     USB drives and optical media
  #   • Add `programs.direnv.enable = true;` for per-directory
  #     dev environments (great for multi-project setups)
  #   • Add `services.flatpak.enable = true;` for Flatpak support
  #     (useful for apps not yet packaged in Nix)
  # ═══════════════════════════════════════════════════════
  programs.firefox.enable = true;
  programs.starship.enable = true;
  # programs.starship.enableBashIntegration = true;
  # programs.starship.enableZshIntegration = true;

  # ═══════════════════════════════════════════════════════
  # 15. HOME MANAGER (user-level config)
  #
  # Home Manager manages dotfiles, user packages, and user-level
  # services. It uses the same Nix language but applies to a
  # specific user's home directory (~/.config, ~/.local, etc.).
  #
  # useGlobalPkgs = true  → user packages use the same nixpkgs
  #                           as system (consistent versions)
  # useUserPackages = true → home.packages are installed
  #
  # WHAT BELONGS HERE vs environment.systemPackages:
  #   Home Manager: editors, languages, CLI tools, dotfiles,
  #     user services (git config, ssh config, tmux, starship)
  #   System: browsers, DE extensions, system daemons, drivers
  #
  # FUTURE IMPROVEMENTS:
  #   • Add `home.packages = with pkgs; [ ... ];` for personal
  #     dev tools: nodejs, python, rust, zig, bun, uv, gcc,
  #     clang, llvm, typescript, bat, fzf, ripgrep, btop, etc.
  #   • Add EasyEffects declarative config:
  #       xdg.configFile."EasyEffects/output/equalizer.json".source =
  #         pkgs.writeText "equalizer.json" ''{ ... }'';
  #       xdg.configFile."EasyEffects/input/mic-denoise.json".source =
  #         pkgs.writeText "mic-denoise.json" ''{ ... }'';
  #   • Add git config:
  #       programs.git = {
  #         enable = true;
  #         userName = "naranyala";
  #         userEmail = "naranyala@email.com";
  #         extraConfig = {
  #           init.defaultBranch = "main";
  #           core.editor = "nvim";
  #         };
  #       };
  #   • Add tmux config:
  #       programs.tmux = {
  #         enable = true;
  #         clock24 = true;
  #         keyMode = "vi";
  #         extraConfig = ''
  #           set -g mouse on
  #           bind | split-window -h
  #           bind - split-window -v
  #         '';
  #       };
  #   • Add zsh as shell with plugins:
  #       programs.zsh = {
  #         enable = true;
  #         oh-my-zsh = {
  #           enable = true;
  #           plugins = [ "git" "z" "sudo" ];
  #         };
  #       };
  #   • Add SSH config:
  #       programs.ssh = {
  #         enable = true;
  #         extraConfig = ''
  #           Host github.com
  #             IdentityFile ~/.ssh/id_ed25519
  #         '';
  #       };
  #   • Add Neovim plugins via `programs.neovim.plugins`
  #   • Add `home.file.".foo".source = ./dotfiles/foo;` for
  #     dotfiles not covered by home-manager modules
  #   • Add `services.syncthing.enable = true;` for file sync
  #     between machines (like Dropbox but self-hosted)
  #   • Add `services.gpg-agent.enable = true;` for GPG/SSH agent
  #   • Add `services.mpris-proxy.enable = true;` for Bluetooth
  #     media key control (play/pause from headset)
  #   • Add `home.pointerCursor` to sync cursor theme across
  #     GTK, Qt, and X11 apps:
  #       home.pointerCursor = {
  #         name = "Adwaita";
  #         package = pkgs.adwaita-icon-theme;
  #         gtk.enable = true;
  #         x11.enable = true;
  #       };
  # ═══════════════════════════════════════════════════════
  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;

    users.naranyala = { pkgs, config, ... }: {
      home.stateVersion = "25.05";

      home.sessionPath = [
        "${config.home.homeDirectory}/.local/bin"
        "${config.home.homeDirectory}/.bun/bin"
      ];

      home.shellAliases = {
        # NixOS rebuild helpers
        nx-switch = "sudo nixos-rebuild switch";
        nx-edit   = "sudo nvim /etc/nixos/configuration.nix";
        nx-gc     = "sudo nix-collect-garbage -d";
        nx-clean  = "sudo nix-collect-garbage -d && sudo nix-store --optimize";
        update    = "sudo nixos-rebuild switch --upgrade";

        # Quick git
        gs = "git status -sb";
        gp = "git push";

        ll = "ls -la";
      };

      programs.neovim = {
        enable = true;
        defaultEditor = true;
        viAlias = true;
        vimAlias = true;
        # plugins = with pkgs.vimPlugins; [
        #   telescope-nvim
        #   nvim-treesitter.withAllGrammars
        #   nvim-lspconfig
        #   harpoon
        # ];
        # extraConfig = ''
        #   set number relativenumber
        #   set tabstop=2 shiftwidth=2 expandtab
        # '';
      };

      # Set wallpaper via home-manager:
      # dconf.settings = {
      #   "org/gnome/desktop/background" = {
      #     picture-uri = "file://${config.home.homeDirectory}/wallpaper.jpg";
      #     picture-options = "zoom";
      #   };
      # };

      # User-level Firefox (separate profile from system):
      programs.firefox.enable = true;

# Personal dev tools — keep only user-specific apps
      # (glib, dbus, mesa, alsa-lib, gtk3 already in systemPackages)
      home.packages = with pkgs; [
        zenity

        # ── KDE Media ────────────────────────────────────────
        kdePackages.kdialog
        kdePackages.kdenlive

        # ── Media Tools ─────────────────────────────────
        ffmpeg-full
        mediainfo

        # ── Languages / Runtimes ──────────────────────
        # nodejs_24
        bun
        python314
        uv
        ruff
        # rustup
        # cargo-tauri

        # ── Build Tools ─────────────────────────────────
        # gcc
        # clang
        # binutils
        man-db
        valgrind
        cppcheck
        llvm
        zig
        # odin
        # vlang
        cmake

        # ── AI / ML ────────────────────────────────────
        # ollama
        # llama-cpp

        # ── Database ────────────────────────────────
        # dbeaver-bin
        # dbgate
        sqlite
        duckdb
        postgresql_17

        # ── CLI Utilities ──────────────────────────────
        delta
        bat
        fd
        fzf
        ripgrep
        btop
        fastfetch
        starship
        xclip
        md2pdf
        vlc
        # vim
        wget
        git
        unzip
        tree
        ncdu
        jq
        tldr

        # ── Cloud / Network ─────────────────────────
        # cloudflare-warp

        # ── AI CLI ─────────────────────────────────
        # codex

        # ── Editors ────────────────────────────────
        # gedit

        # ── Remote Work ────────────────────────────────
        # remmina  # RDP/VNC client for Windows servers
        # teamviewer
      ];
    };
  };

  # ═══════════════════════════════════════════════════════
  # 16. STATE VERSION
  #
  # DO NOT change this unless you know what you're doing.
  # This tells NixOS which version of the config format was
  # current when this file was created. Changing it on a
  # working system can break things.
  #
  # Only bump when:
  #   • You upgrade to a new NixOS release (25.05 → 25.11)
  #   • The NixOS manual tells you to
  #
#   If you accidentally change it, revert to the original
  #   and run `sudo nixos-rebuild switch` to fix.
  # ═══════════════════════════════════════════════════════

  # OpenGL + CUDA for AI apps and browsers
  hardware.opengl.enable = true;
  services.ollama.enable = true;

  system.stateVersion = "25.05";
}
