
# tmux config

## easy to reload
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

## align with waybar position
set -g status-position top
set -g mouse on

## better super key
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

## reset index one
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

## remember last dir path
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

## Move window left or right with Ctrl+Left/Right
bind-key -n C-Left swap-window -t -1\; select-window -t -1
bind-key -n C-Right swap-window -t +1\; select-window -t +1

## simple theme
set -g window-status-format "#I:#W"
set -g window-status-current-format "#I:#W"
set -g status-style bg=white,fg=black
setw -g window-status-current-style bg=colour2,fg=black,bold

