#!/usr/bin/env bash
#
# kitty-setup.sh — Install Kitty terminal and configure equal-width top tabs
#

set -euo pipefail

TAB_WIDTH=20
KITTY_CONF_DIR="${HOME}/.config/kitty"
KITTY_CONF_FILE="${KITTY_CONF_DIR}/kitty.conf"

install_kitty() {
    echo "[*] Installing Kitty..."
    if command -v apt-get >/dev/null 2>&1; then
        sudo apt-get update
        sudo apt-get install -y kitty
    elif command -v dnf >/dev/null 2>&1; then
        sudo dnf install -y kitty
    elif command -v pacman >/dev/null 2>&1; then
        sudo pacman -Sy --noconfirm kitty
    else
        echo "[-] Unsupported package manager. Please install Kitty manually."
        exit 1
    fi
}

configure_kitty() {
    echo "[*] Configuring Kitty..."
    mkdir -p "${KITTY_CONF_DIR}"

    if [[ -f "${KITTY_CONF_FILE}" ]]; then
        cp "${KITTY_CONF_FILE}" "${KITTY_CONF_FILE}.bak.$(date +%s)"
        echo "    Existing config backed up."
    fi

    cat > "${KITTY_CONF_FILE}" <<EOF
# Kitty configuration generated by kitty-setup.sh

# Tabs at the top
tab_bar_edge top

# Equal-width tabs
tab_bar_min_tab_width ${TAB_WIDTH}
tab_bar_max_tab_width ${TAB_WIDTH}

# Boxy style
tab_bar_style separator
tab_separator " | "
tab_bar_align center

# Keep titles uniform (just index)
tab_title_template "{index}"

# Optional: activity indicator
tab_activity_symbol ●
EOF

    echo "    Config written to ${KITTY_CONF_FILE}"
}

reload_kitty() {
    if pgrep kitty >/dev/null 2>&1; then
        echo "[*] Reloading Kitty config..."
        kill -SIGUSR1 $(pgrep kitty | head -n1)
    else
        echo "[*] Kitty not running. Start it to see changes."
    fi
}

install_kitty
configure_kitty
reload_kitty

echo "[✓] Kitty installation and configuration complete."

